### ISSUE TITLE
maptalks-server start /path/to/instance/config.json , 会报缺少 .forever错误

### ISSUE THREAD

**Issue by fuzhenn** [maptalks/mapresty#10]
报错信息:
```
no such file or directory, open 'C:\instance\.forever\app.log'
```
手动新建.forever和相应的log文件后解决

请修改此问题

**Comment by wsw0108** [comment]
![image](https://cloud.githubusercontent.com/assets/4977975/18154170/17134742-7035-11e6-8dc9-3b7875fa189e.png)

我这里没问题啊
